Check for finger position errors

diff --git a/slapsegiii/validation/validate b/slapsegiii/validation/validate
--- a/slapsegiii/validation/validate
+++ b/slapsegiii/validation/validate
@@ -1242,6 +1242,35 @@ check_orientation_log_errors()
 	return ${has_failure_rv}
 }
 
+# Return 1 if finger is not possible with hand position
+# 1: Hand FGP
+# 2: Finger FGP
+check_hand_finger_code()
+{
+	if [ ${#} -ne 2 ]; then
+		echo "Usage: ${FUNCNAME[0]} <hand_fgp> <finger_fgp>"
+		return 1
+	fi
+	local hand="${1}"
+	local finger="${2}"
+
+	if [ "${hand}" -eq 13 ] || [ "${hand}" -eq 21 ] || [ "${hand}" -eq 26 ]
+	then
+		if [ "${finger}" -lt 2 ] || [ "${finger}" -gt 5 ]; then
+			return 1
+		fi
+	elif [ "${hand}" -eq 14 ] || [ "${hand}" -eq 23 ] || \
+	[ "${hand}" -eq 28 ]; then
+		if [ "${finger}" -lt 7 ] || [ "${finger}" -gt 10 ]; then
+			return 1
+		fi
+	elif [ "${hand}" -eq 15 ]; then
+		if [ "${finger}" -ne 1 ] && [ "${finger}" -ne 6 ]; then
+			return 1
+		fi
+	fi
+}
+
 # Check that there were no coordinate errors or nonzero return values logged
 # during segmentation.
 # @return 1 if there are failure return values
@@ -1261,14 +1290,16 @@ check_segmentation_log_errors()
 		local is_rotated=0
 		local has_nonrectangular_coordiantes=0
 		local has_irregular_coordinates=0
+		local has_frgp_error=0
 		local missing_deficiencies=0
 		local has_deficiencies=0
 
 		{
 		read -r # Read header line
 		while read -r line; do
-			read -r name rv errors scode deficiencies quantity <<< \
-			    "$(awk -F, '{print $1,$3,$16,$14,$17,$18}' <<< \
+			read -r name rv frgp errors scode deficiencies \
+			    quantity <<< \
+			    "$(awk -F, '{print $1,$3,$5,$16,$14,$17,$18}' <<< \
 			    "${line}")"
 
 			# Ensure that a deficiency is set when returning
@@ -1283,6 +1314,18 @@ check_segmentation_log_errors()
 				    "0000" ]; then
 					has_deficiencies=1
 				fi
+			fi
+
+			# Check finger positions
+			local hand_fgp
+			hand_fgp="$(cut -f4 -d_ <<< "${name}")"
+			# Canary images are assumed to be right hand
+			if grep -q canary <<< "${name}"; then
+				hand_fgp=13
+			fi
+			if ! check_hand_finger_code "${hand_fgp}" "${frgp}";
+			then
+				has_frgp_error=1
 			fi
 
 			# Only check for position errors with "Success" or
@@ -1328,6 +1371,7 @@ check_segmentation_log_errors()
 		    [ ${has_nonrectangular_coordiantes} -eq 1 ] || \
 		    [ ${has_irregular_coordinates} -eq 1 ] || \
 		    [ ${has_deficiencies} -eq 1 ] || \
+		    [ ${has_frgp_error} -eq 1 ] || \
 		    [ ${missing_deficiencies} -eq 1 ]; then
 		    	local p="${output_dir}"/segments-${type}.log
 		    	if [ "${error_message}" != "" ]; then
@@ -1361,6 +1405,12 @@ check_segmentation_log_errors()
 			error_message+='Attempt] but did not set a Deficiency.'
 		fi
 
+		if [ ${has_frgp_error} -eq 1 ]; then
+			error_message+='\n \x2A Set an invalid FrictionRidge'
+			error_message+="GeneralizedPosition (e.g. Unknown (0) "
+			error_message+="or an FGP from the wrong hand."
+		fi
+
 		if [ ${has_deficiencies} -eq 1 ]; then
 			error_message+='\n \x2A returned Success but set a '
 			error_message+='Deficiency.'
@@ -1372,7 +1422,7 @@ check_segmentation_log_errors()
 	done
 
 	if [ "${error_message}" != "" ]; then
-		fail "${error_message}"
+		fail "${error_message}\n"
 	fi
 
 	return ${has_failure_rv}
