Options to print instructions (overall + encrypt)

diff --git a/slapsegiii/validation/validate b/slapsegiii/validation/validate
--- a/slapsegiii/validation/validate
+++ b/slapsegiii/validation/validate
@@ -1508,6 +1508,64 @@ print_footer()
 	font_reset
 }
 
+print_encryption()
+{
+	local tar_file
+	if ! tar_file="$(get_tarball_name)"; then
+		tar_file="slapsegiii_validation_nullimpl_0001.tar.xz"
+	fi
+
+	# Sign + encrypt example
+	echo "Example of signing and encrypting with GnuPG:"
+	echo "  gpg --output ${tar_file}.asc \\"
+	echo "      --default-key <!-- YOUR EMAIL ADDRESS --> \\"
+	echo "      --recipient <!-- YOUR EMAIL ADDRESS --> \\"
+	echo "      --recipient slapseg@nist.gov \\"
+	echo "      --armor --sign --encrypt ${tar_file}"
+	echo
+
+	# Extract public key example
+	local lib_name
+	if ! lib_name="$(get_core_library_name)"; then
+		lib_name="libslapiii_nullimpl_0001.so"
+	fi
+	lib_name="$(basename "${lib_name}" .so)"
+	echo "Example of extracting public key with GnuPG:"
+	echo "  gpg --output ${lib_name}_public_key.asc \\"
+	echo "      --armor --export <!-- YOUR EMAIL ADDRESS -->"
+	echo
+
+	# Export key fingerprint example
+	echo "Example of extracting fingerprint from public key with GnuPG:"
+	echo "  gpg --fingerprint <!-- YOUR EMAIL ADDRESS --> | grep '^ '"
+}
+
+# Print instructions to the console
+print_instructions()
+{
+	echo "$0 clean"
+	echo -n " - Restores validation directory to original state, removing "
+	echo "any previous "
+	echo "   output, but leaving copied libraries and configurations."
+	echo
+	echo "$0 encrypt"
+	echo " - Print sample signing and encryption instructions for GnuPG."
+	echo
+	echo "Instructions"
+	echo "============"
+	echo " 1. Copy required files:"
+	echo -n "    a. Place all needed libraries in 'lib/', including your "
+	echo "properly named "
+	echo "       SlapSeg III core library."
+	echo " 2. Run './validate'."
+	echo "    a. Successful? Sign and encrypt the generated archive."
+	echo "    b. Unsuccessful? Work to resolve the listed errors, run"
+	echo "       './validate clean', and repeat these steps."
+	echo -n " 3. Email the signed and encrypted file along with your "
+	echo "public key to"
+	echo "    slapseg@nist.gov."
+}
+
 # Print message when validation version couldn't be checked
 print_couldnt_check_version()
 {
@@ -1587,18 +1645,30 @@ move_back_dirs()
 trap move_back_dirs INT
 
 check_wd
+cd "${wd}" || exit 1
 read -r validation_version < "${wd}"/VERSION
 print_header
 
-if [ $# -ne 0 ]; then
-	if [ "$1" == "clean" ]; then
+if [ "${#}" -ne 0 ]; then
+	if [ "${1}" == "clean" ]; then
 		clean_previous_attempts
-		printf '=%.0s' $(seq 1 80)
-		echo
+		exit
+	elif [ "${1}" == "encrypt" ]; then
+		print_encryption
+		exit
+	elif [ "${1}" == "help" ]; then
+		print_instructions
 		exit
 	else
-		echo "Usage: $0 [clean]"
+		echo "Usage: ${0} [clean|encrypt|help]"
+		print_instructions
 		exit 1
+	fi
+else
+	# Quick check to see if it looks like we're fresh
+	if ! core_library_present; then
+		print_instructions
+		exit
 	fi
 fi
 
