Don't warn about failure return values on canary images.

diff --git a/slapsegiii/validation/validate b/slapsegiii/validation/validate
--- a/slapsegiii/validation/validate
+++ b/slapsegiii/validation/validate
@@ -851,11 +851,16 @@ check_orientation_log_errors()
 		{
 		read # Read header line
 		while read line; do
-			read rv orientation <<< \
-			    $(awk -F, '{print $3,$5}' <<< $line)
+			read name rv orientation <<< \
+			    $(awk -F, '{print $1,$3,$5}' <<< $line)
 
 			if [ ${rv} != 0 ]; then
-				has_failure_rv=1
+				# We fully expect failures on canary images,
+				# so don't warn about them.
+				if [ $(grep -q canary <<< ${name}; echo $?) -ne \
+				    0 ]; then
+					has_failure_rv=1
+				fi
 			fi
 
 			# We only check orientation logs if they are supported,
@@ -958,8 +963,8 @@ check_segmentation_log_errors()
 		{
 		read # Read header line
 		while read line; do
-			read rv errors scode deficiencies quantity <<< \
-			    $(awk -F, '{print $3,$16,$14,$17,$18}' <<< $line)
+			read name rv errors scode deficiencies quantity <<< \
+			    $(awk -F, '{print $1,$3,$16,$14,$17,$18}' <<< $line)
 
 			# Ensure that a deficiency is set when returning
 			# RequestRecapture and RequestRecaptureWithAttempt
@@ -978,7 +983,12 @@ check_segmentation_log_errors()
 			# Only check for position errors with "Success" or
 			# "RequestRecaptureWithAttempt"
 			if [ ${rv} -ne 0 ] && [ ${rv} -ne 3 ]; then
-				has_failure_rv=1
+				# We fully expect failures on canary images,
+				# so don't warn about them.
+				if [ $(grep -q canary <<< ${name}; echo $?) -ne \
+				    0 ]; then
+					has_failure_rv=1
+				fi
 				continue
 			fi
 
