Image dir will always exist.

diff --git a/slapsegiii/validation/validate b/slapsegiii/validation/validate
--- a/slapsegiii/validation/validate
+++ b/slapsegiii/validation/validate
@@ -309,67 +309,37 @@ okay()
 # Check that images have been downloaded, placed in the correct spot, etc.
 check_for_images()
 {
-	# Check for data
 	echo -n "Checking for validation images... "
-	if ! [ -d "${wd}/${validation_image_dir}" ]; then
-		# If directory doesn't exist, maybe user didn't expand archive
-		local image_archive
-		image_archive=$(ls -r \
-		    "${wd}"/${validation_image_download_prefix}* 2> /dev/null)
-		if [ "${image_archive}" != "" ]; then
-			font_yellow
-			echo "[DEFER]"
-			font_reset
-			while read -r i; do
-				echo -n "Expanding $(basename "${i}")... "
-				if ! tar xf "${i}" > /dev/null 2>&1; then
-					fail "Failed to expand ${i}"
-				else
-					okay
-				fi
-			done < <(find "${wd}" -maxdepth 1 -name \
-			    "${validation_image_download_prefix}*")
 
-			check_for_images
-			return
-		else
-			msg="Cannot find validation images. You must request "
-			msg+="them from NIST's website and place them within:"
-			fail "${msg}" "${wd}" "The URL is:" \
-			    ${validation_image_request_url}
-		fi
-	else
-		# If the directory does exist, check that every archive present
-		# has been expanded
-		local has_deferred=0
-		while read -r i; do
-		    	local regex=".*\/${validation_image_download_prefix}"
-		    	regex+="\(.*\)-.\+.tar.gz"
-			local kind
-			# shellcheck disable=SC2001
-			kind=$(sed "s/${regex}/\1/" <<< "${i}")
-			if ! [ -e \
-			    "${wd}/${validation_image_dir}/VERSION-${kind}" ];
-			    then
-			    	if [ ${has_deferred} -eq 0 ]; then
-			    		font_yellow
-	    				echo "[DEFER]"
-	    				font_reset
-	    				has_deferred=1
-	    			fi
-
-				echo -n "Expanding $(basename "${i}")... "
-				if ! tar xf "${i}" > /dev/null 2>&1; then
-					fail "Failed to expand ${i}"
-					return
-				else
-					okay
-					return
-				fi
+	# Check that every archive present has been expanded
+	local has_deferred=0
+	while read -r i; do
+		local regex=".*\/${validation_image_download_prefix}"
+		regex+="\(.*\)-.\+.tar.gz"
+		local kind
+		# shellcheck disable=SC2001
+		kind=$(sed "s/${regex}/\1/" <<< "${i}")
+		if ! [ -e \
+		    "${wd}/${validation_image_dir}/VERSION-${kind}" ];
+		    then
+			if [ ${has_deferred} -eq 0 ]; then
+				font_yellow
+				echo "[DEFER]"
+				font_reset
+				has_deferred=1
 			fi
-		done < <(find "${wd}" -maxdepth 1 -name \
-		    "${validation_image_download_prefix}*")
-	fi
+
+			echo -n "Expanding $(basename "${i}")... "
+			if ! tar xf "${i}" > /dev/null 2>&1; then
+				fail "Failed to expand ${i}"
+				return
+			else
+				okay
+				return
+			fi
+		fi
+	done < <(find "${wd}" -maxdepth 1 -name \
+	    "${validation_image_download_prefix}*")
 
 	okay
 }
